image:
  - ubuntu2004

cache:
  - $HOME/.apt
  - $HOME/.cache/pip/

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  - sudo apt update -qq;
  - if [[ ! -d $HOME/.apt/ ]]; then
    mkdir $HOME/.apt/;
    sudo apt install --download-only -y python3-pip python3-setuptools python3-venv doxygen doxygen-doc doxygen-latex doxygen-gui graphviz libgl1-mesa-dev clang clang-tools build-essential gcc-10 g++-10;
    sudo cp -r  /var/cache/apt/archives $HOME/.apt;
    else
    sudo cp -r $HOME/.apt /var/cache/apt/archives;
    fi

before_build:
  - sudo apt install -qq -y python3-pip python3-setuptools python3-venv doxygen doxygen-doc doxygen-latex doxygen-gui graphviz libgl1-mesa-dev clang clang-tools build-essential g++-10 gcc-10;
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
  - ${APPVEYOR_BUILD_FOLDER}/scripts/install_liburing.sh
  - ${APPVEYOR_BUILD_FOLDER}/scripts/install_cppcoro.sh

  - mkdir ${APPVEYOR_BUILD_FOLDER}/build
  - cd ${APPVEYOR_BUILD_FOLDER}/build
  - cmake ..

build_script:
  - cd ${APPVEYOR_BUILD_FOLDER}/build
  - make -j8

test_script:
  - cd ${APPVEYOR_BUILD_FOLDER}/build
  - ctest
